[package]
name = "export"
version = "0.1.1"
edition = "2021"
description = "RITE exporter trait"
readme = "README.md"
repository = "https://github.com/CIAO-systems/rite"
license = "Apache-2.0"

[dependencies]
model = { git = "https://github.com/CIAO-systems/rite-lib-model.git" }

